[package]
name = "simple_monitor"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.4"
dotenv = "0.15.0"
nvml-wrapper = "0.11.0"
serde = { version = "1.0.219", features = ["derive"] }
sysinfo = "0.35.2"
tokio = { version = "1.46.1", features = ["full"] }
