@echo off
REM ================================================
REM Simple Monitor - Windows Configuration Helper
REM ================================================

echo ================================================
echo          Simple Monitor Configuration
echo ================================================
echo.
echo This script will help you configure Simple Monitor
echo by creating a .env file with your settings.
echo.

REM Check if .env already exists
if exist ".env" (
    echo Found existing .env file:
    echo.
    type .env
    echo.
    set /p "overwrite=Overwrite existing .env file? (y/N): "
    if /i not "%overwrite%"=="y" (
        echo Configuration cancelled.
        pause
        exit /b
    )
    echo.
)

echo ================================================
echo                   HOST Setting
echo ================================================
echo.
echo Choose your HOST setting:
echo   1. Local only (127.0.0.1) - Default, secure
echo   2. Network access (0.0.0.0) - Allow other devices to connect
echo.
set /p "host_choice=Enter choice (1 or 2): "

if "%host_choice%"=="2" (
    set "HOST=0.0.0.0"
    echo Selected: Network access (0.0.0.0)
) else (
    set "HOST=127.0.0.1"
    echo Selected: Local only (127.0.0.1)
)

echo.
echo ================================================
echo                   PORT Setting  
echo ================================================
echo.
echo Choose your PORT setting:
echo   1. Default (3000)
echo   2. Alternative (8080)
echo   3. Custom port
echo.
set /p "port_choice=Enter choice (1, 2, or 3): "

if "%port_choice%"=="2" (
    set "PORT=8080"
    echo Selected: Port 8080
) else if "%port_choice%"=="3" (
    set /p "custom_port=Enter custom port (1024-65535): "
    set "PORT=%custom_port%"
    echo Selected: Port %custom_port%
) else (
    set "PORT=3000"
    echo Selected: Port 3000
)

echo.
echo ================================================
echo                Creating .env file
echo ================================================

REM Create the .env file
echo # Simple Monitor Configuration > .env
echo # Generated by configure-windows.bat >> .env
echo. >> .env
echo # Host to bind the web server to >> .env
echo # Use 127.0.0.1 for localhost only (default) >> .env
echo # Use 0.0.0.0 to allow external connections >> .env
echo HOST=%HOST% >> .env
echo. >> .env
echo # Port for the web server (default: 3000) >> .env
echo PORT=%PORT% >> .env

echo Created .env file with your settings:
echo.
type .env
echo.

echo ================================================
echo                   Summary
echo ================================================
echo.
echo Configuration complete!
echo.
echo Your monitor will be available at:
if "%HOST%"=="127.0.0.1" (
    echo   http://localhost:%PORT%
    echo   (Local access only)
) else (
    echo   http://localhost:%PORT% (local)
    echo   http://YOUR-IP-ADDRESS:%PORT% (network)
    echo   (Network access enabled)
)
echo.
echo To start the monitor:
echo   1. Double-click simple_monitor.exe
echo   2. Or double-click start-windows.bat
echo.
echo Press any key to exit...
pause >nul 